swagger: "2.0"
info:
  title: inventory-backend
  description: This is the documentation for inventory backend
  version: 1.0.0
  servers: 
    url: "http://localhost:8000/api/v1"
    description: This is my local server
    
schemes: [http]

paths:
# Farmer
  /farmer/get:
    post:
      summary: return data of farmers
      description: It returns a data of all farmer
      responses:
        200:
          description: Successfully get all data of farmer
    
        500:
          description: Interner Server error
        401:
          description: User is not login
  
  /farmer/:
    post:
      summary: Creating new farmer
      description: This endpoint is used to create new farmer
      produces:
        - application/json
      consumes:
        -application/json
      parameters:
      - in: body
        name: farmer data data
        schema:
          $ref: '#definitions/farmerSchema'
      responses:
        200:
          description: Successfully created farmer
        500:
          description: Internal Server error
        401:
          description: User is not login

  